export const users = [
  {
    id: 1,
    username: "admin",
    fullName: "Admin User",
    email: "admin@example.com",
    avatar: null,
    role: "admin",
    permissions: [
      "view_projects",
      "create_projects",
      "edit_projects",
      "delete_projects",
      "view_tasks",
      "create_tasks",
      "edit_tasks",
      "delete_tasks",
      "view_worklogs",
      "create_worklogs",
      "edit_worklogs",
      "delete_worklogs",
      "view_performance",
      "view_settings",
    ],
  },
  {
    id: 2,
    username: "manager",
    fullName: "Project Manager",
    email: "manager@example.com",
    avatar: null,
    role: "manager",
    permissions: [
      "view_projects",
      "create_projects",
      "edit_projects",
      "view_tasks",
      "create_tasks",
      "edit_tasks",
      "view_worklogs",
      "create_worklogs",
      "edit_worklogs",
      "view_performance",
    ],
  },
  {
    id: 3,
    username: "developer",
    fullName: "Developer",
    email: "developer@example.com",
    avatar: null,
    role: "developer",
    permissions: [
      "view_projects",
      "view_tasks",
      "create_tasks",
      "edit_tasks",
      "view_worklogs",
      "create_worklogs",
      "edit_worklogs",
    ],
  },
  {
    id: 4,
    username: "tester",
    fullName: "QA Tester",
    email: "tester@example.com",
    avatar: null,
    role: "tester",
    permissions: [
      "view_projects",
      "view_tasks",
      "create_tasks",
      "edit_tasks",
      "view_worklogs",
      "create_worklogs",
    ],
  },
];

export const roles = [
  {
    id: "admin",
    name: "Administrator",
    description: "Full system access",
  },
  {
    id: "manager",
    name: "Project Manager",
    description: "Can manage projects and tasks",
  },
  {
    id: "developer",
    name: "Developer",
    description: "Can work on tasks and log work",
  },
  {
    id: "tester",
    name: "QA Tester",
    description: "Can test and report issues",
  },
];
