export const worklogs = [
  {
    id: "WL001",
    taskId: "T001",
    userId: "U001",
    hours: 4.5,
    date: "2024-03-15",
    description:
      "Implemented user authentication system and login functionality",
    createdAt: "2024-03-15T09:00:00Z",
    userName: "John Doe",
    userAvatar: "https://i.pravatar.cc/150?img=1",
    taskName: "Implement Authentication",
    taskStatus: "completed",
    projectName: "Project Management System",
    projectStatus: "active",
  },
  {
    id: "WL002",
    taskId: "T002",
    userId: "U002",
    hours: 3.0,
    date: "2024-03-15",
    description:
      "Created responsive dashboard layout and navigation components",
    createdAt: "2024-03-15T10:30:00Z",
    userName: "Jane Smith",
    userAvatar: "https://i.pravatar.cc/150?img=2",
    taskName: "Dashboard Development",
    taskStatus: "in_progress",
    projectName: "Project Management System",
    projectStatus: "active",
  },
  {
    id: "WL003",
    taskId: "T003",
    userId: "U003",
    hours: 5.0,
    date: "2024-03-15",
    description: "Developed task management system with CRUD operations",
    createdAt: "2024-03-15T11:45:00Z",
    userName: "Mike Johnson",
    userAvatar: "https://i.pravatar.cc/150?img=3",
    taskName: "Task Management Module",
    taskStatus: "completed",
    projectName: "Project Management System",
    projectStatus: "active",
  },
  {
    id: "WL004",
    taskId: "T004",
    userId: "U001",
    hours: 2.5,
    date: "2024-03-16",
    description: "Fixed bugs in project creation workflow",
    createdAt: "2024-03-16T08:15:00Z",
    userName: "John Doe",
    userAvatar: "https://i.pravatar.cc/150?img=1",
    taskName: "Bug Fixes",
    taskStatus: "completed",
    projectName: "Project Management System",
    projectStatus: "active",
  },
  {
    id: "WL005",
    taskId: "T005",
    userId: "U002",
    hours: 4.0,
    date: "2024-03-16",
    description: "Implemented real-time notifications system",
    createdAt: "2024-03-16T09:30:00Z",
    userName: "Jane Smith",
    userAvatar: "https://i.pravatar.cc/150?img=2",
    taskName: "Notifications System",
    taskStatus: "in_progress",
    projectName: "Project Management System",
    projectStatus: "active",
  },
  {
    id: "WL006",
    taskId: "T006",
    userId: "U003",
    hours: 3.5,
    date: "2024-03-16",
    description: "Created user profile management interface",
    createdAt: "2024-03-16T10:45:00Z",
    userName: "Mike Johnson",
    userAvatar: "https://i.pravatar.cc/150?img=3",
    taskName: "User Profile Module",
    taskStatus: "completed",
    projectName: "Project Management System",
    projectStatus: "active",
  },
  {
    id: "WL007",
    taskId: "T007",
    userId: "U001",
    hours: 6.0,
    date: "2024-03-17",
    description: "Developed advanced search and filtering functionality",
    createdAt: "2024-03-17T08:00:00Z",
    userName: "John Doe",
    userAvatar: "https://i.pravatar.cc/150?img=1",
    taskName: "Search Implementation",
    taskStatus: "completed",
    projectName: "Project Management System",
    projectStatus: "active",
  },
  {
    id: "WL008",
    taskId: "T008",
    userId: "U002",
    hours: 4.5,
    date: "2024-03-17",
    description: "Implemented data visualization components",
    createdAt: "2024-03-17T09:15:00Z",
    userName: "Jane Smith",
    userAvatar: "https://i.pravatar.cc/150?img=2",
    taskName: "Data Visualization",
    taskStatus: "in_progress",
    projectName: "Project Management System",
    projectStatus: "active",
  },
  {
    id: "WL009",
    taskId: "T009",
    userId: "U003",
    hours: 3.0,
    date: "2024-03-17",
    description: "Created API documentation and integration tests",
    createdAt: "2024-03-17T10:30:00Z",
    userName: "Mike Johnson",
    userAvatar: "https://i.pravatar.cc/150?img=3",
    taskName: "API Documentation",
    taskStatus: "completed",
    projectName: "Project Management System",
    projectStatus: "active",
  },
  {
    id: "WL010",
    taskId: "T010",
    userId: "U001",
    hours: 5.5,
    date: "2024-03-18",
    description: "Developed team collaboration features",
    createdAt: "2024-03-18T08:45:00Z",
    userName: "John Doe",
    userAvatar: "https://i.pravatar.cc/150?img=1",
    taskName: "Team Collaboration",
    taskStatus: "completed",
    projectName: "Project Management System",
    projectStatus: "active",
  },
  {
    id: "WL011",
    taskId: "T011",
    userId: "U002",
    hours: 4.0,
    date: "2024-03-18",
    description: "Implemented file upload and management system",
    createdAt: "2024-03-18T09:30:00Z",
    userName: "Jane Smith",
    userAvatar: "https://i.pravatar.cc/150?img=2",
    taskName: "File Management",
    taskStatus: "in_progress",
    projectName: "Project Management System",
    projectStatus: "active",
  },
  {
    id: "WL012",
    taskId: "T012",
    userId: "U003",
    hours: 3.5,
    date: "2024-03-18",
    description: "Created automated testing suite",
    createdAt: "2024-03-18T10:15:00Z",
    userName: "Mike Johnson",
    userAvatar: "https://i.pravatar.cc/150?img=3",
    taskName: "Testing Suite",
    taskStatus: "completed",
    projectName: "Project Management System",
    projectStatus: "active",
  },
  {
    id: "WL013",
    taskId: "T013",
    userId: "U001",
    hours: 4.5,
    date: "2024-03-19",
    description: "Developed performance monitoring dashboard",
    createdAt: "2024-03-19T08:00:00Z",
    userName: "John Doe",
    userAvatar: "https://i.pravatar.cc/150?img=1",
    taskName: "Performance Dashboard",
    taskStatus: "completed",
    projectName: "Project Management System",
    projectStatus: "active",
  },
  {
    id: "WL014",
    taskId: "T014",
    userId: "U002",
    hours: 3.0,
    date: "2024-03-19",
    description: "Implemented user activity tracking",
    createdAt: "2024-03-19T09:15:00Z",
    userName: "Jane Smith",
    userAvatar: "https://i.pravatar.cc/150?img=2",
    taskName: "Activity Tracking",
    taskStatus: "in_progress",
    projectName: "Project Management System",
    projectStatus: "active",
  },
  {
    id: "WL015",
    taskId: "T015",
    userId: "U003",
    hours: 5.0,
    date: "2024-03-19",
    description: "Created advanced reporting system",
    createdAt: "2024-03-19T10:30:00Z",
    userName: "Mike Johnson",
    userAvatar: "https://i.pravatar.cc/150?img=3",
    taskName: "Reporting System",
    taskStatus: "completed",
    projectName: "Project Management System",
    projectStatus: "active",
  },
];
