import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

// Translations
const translations = {
  en: {
    // Navigation & Paths
    navProjects: "Projects",
    navTasks: "Tasks",
    navPerformance: "Performance",
    navWorklogs: "Work Logs",
    navSettings: "Settings",
    navProfile: "Profile",
    navNotifications: "Notifications",
    navAppearance: "Appearance",
    navPrivacy: "Privacy",
    navTimezone: "Time Zone",
    navSecurity: "Security",

    // Common
    commonSettings: "Settings",
    commonSave: "Save",
    commonCancel: "Cancel",
    commonEdit: "Edit",
    commonDelete: "Delete",
    commonSearch: "Search",
    commonFilter: "Filter",
    commonReset: "Reset",
    commonLoading: "Loading...",
    commonError: "Error",
    commonSuccess: "Success",

    // Settings Menu
    settingsMyProfile: "My Profile",
    settingsNotifications: "Notifications",
    settingsAppearance: "Appearance",
    settingsPrivacy: "Privacy",
    settingsTimeZone: "Time Zone",
    settingsSecurity: "Security",

    // Profile
    profileFullName: "Full Name",
    profileEmail: "Email Address",
    profilePhone: "Phone",
    profileLocation: "Location",
    profileRole: "Role",
    profileEdit: "Edit Profile",
    profileUpdate: "Update Profile",
    profileUpdateSuccess: "Profile updated successfully",
    profileUpdateFailed: "Failed to update profile",
    profileAbout: "About",

    // Notifications
    notifEmail: "Email Notifications",
    notifPush: "Push Notifications",
    notifDesktop: "Desktop Notifications",
    notifDailyDigest: "Daily Digest",
    notifTaskUpdates: "Task Updates",
    notifProjectUpdates: "Project Updates",
    notifMentions: "Mentions",
    notifComments: "Comments",
    notifMarkAllRead: "Mark all as read",
    notifNoNotifications: "No notifications",
    notifViewAll: "View work logs",
    notifSettings: "Notification Settings",
    notifEnableAll: "Enable All",
    notifDisableAll: "Disable All",
    notifTaskAssigned: "Task Assigned",
    notifTaskCompleted: "Task Completed",
    notifTaskUpdated: "Task Updated",
    notifTaskComment: "New Comment",
    notifProjectCreated: "Project Created",
    notifProjectUpdated: "Project Updated",
    notifProjectDeleted: "Project Deleted",
    notifMemberAdded: "Member Added",
    notifMemberRemoved: "Member Removed",
    notifRoleChanged: "Role Changed",
    notifDeadlineApproaching: "Deadline Approaching",
    notifOverdue: "Task Overdue",
    notifNewMessage: "New Message",
    notifNewReply: "New Reply",
    notifNewMention: "New Mention",
    notifNewAttachment: "New Attachment",
    notifNewInvitation: "New Invitation",
    notifInvitationAccepted: "Invitation Accepted",
    notifInvitationRejected: "Invitation Rejected",

    // Appearance
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    language: "Language",
    fontSize: "Font Size",
    small: "Small",
    fontSizeMedium: "Medium",
    large: "Large",
    density: "Density",
    comfortable: "Comfortable",
    compact: "Compact",
    colorScheme: "Color Scheme",

    // Privacy
    profileVisibility: "Profile Visibility",
    public: "Public",
    teamOnly: "Team Only",
    private: "Private",
    contactInformation: "Contact Information",
    showEmail: "Show Email Address",
    showPhone: "Show Phone Number",
    activity: "Activity",
    showActivity: "Show Activity Status",
    showLocation: "Show Location",

    // Security
    twoFactorAuth: "Two-Factor Authentication",
    enable2FA: "Enable Two-Factor Authentication",
    authMethod: "Authentication Method",
    authenticator: "Authenticator App",
    sms: "SMS",
    email: "Email",
    sessionSettings: "Session Settings",
    sessionTimeout: "Session Timeout",
    minutes: "minutes",
    loginNotifications: "Login Notifications",
    password: "Password",
    changePassword: "Change Password",
    lastChanged: "Last changed",

    // Time Zone
    timezone: "Time Zone",
    dateFormat: "Date Format",
    timeFormat: "Time Format",
    hour12: "12-hour (AM/PM)",
    hour24: "24-hour",
    weekStartsOn: "Week Starts On",
    monday: "Monday",
    sunday: "Sunday",

    // Home Page
    welcomeBack: "Welcome back",
    quickOverview: "Here's a quick overview of your day",
    projects: "Projects",
    ongoing: "ongoing",
    completedTasks: "Completed Tasks",
    today: "today",
    activeMembers: "Active Members",
    members: "members",
    reports: "Reports",
    generated: "generated",
    todaySchedule: "Today's Schedule",
    recentActivity: "Recent Activity",
    dueToday: "Due today",
    quote:
      '"The best way to get started is to quit talking and begin doing." – Walt Disney',

    // Performance Page
    projectName: "Project Name",
    status: "Status",
    progress: "Progress",
    startDate: "Start Date",
    endDate: "End Date",
    manager: "Manager",
    overdueTasks: "Overdue Tasks",
    unknown: "Unknown",
    completed: "Completed",
    inProgress: "In Progress",
    overdue: "Overdue",
    open: "Open",
    totalProjects: "Total Projects",
    averageProgress: "Average Progress",
    projectPerformanceOverview: "Project Performance Overview",
    taskStatusDistribution: "Task Status Distribution",
    monthlyProgress: "Monthly Progress",

    // WorkLogs Page
    project: "Project",
    task: "Task",
    user: "User",
    description: "Description",
    createdAt: "Created At",
    export: "Export",
    exportComingSoon: "Export functionality coming soon",
    totalHours: "Total Hours",
    activeUsers: "Active Users",
    searchWorkLogs: "Search work logs...",
    filters: "Filters",
    active: "Active",
    inactive: "Inactive",

    // Login Page
    projectManagement: "Project Management",
    signInToAccount: "Sign in to your account",
    pleaseInputEmail: "Please input your email!",
    pleaseEnterValidEmail: "Please enter a valid email!",
    pleaseInputPassword: "Please input your password!",
    signIn: "Sign in",
    login: "Login",
    signUp: "Sign Up",
    loginSubtitle: "Welcome back! Please enter your details.",
    name: "Name",
    namePlaceholder: "Enter your name",
    email: "Email",
    emailPlaceholder: "Enter your email",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Confirm your password",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    pleaseInputName: "Please input your name!",
    pleaseConfirmPassword: "Please confirm your password!",
    passwordMinLength: "Password must be at least 6 characters!",
    passwordsDoNotMatch: "The two passwords do not match!",
    loginSuccess: "Login successful!",
    signupSuccess: "Sign up successful!",
    loginFailed: "Login failed",
    signupFailed: "Sign up failed",
    unknownError: "An unknown error occurred",

    // NotFound Page
    pageNotFound: "Sorry, the page you visited does not exist.",
    backToHome: "Back to Home",
    goBack: "Go Back",

    // Project Management Page
    onHold: "On Hold",
    cancelled: "Cancelled",
    development: "Development",
    design: "Design",
    marketing: "Marketing",
    research: "Research",
    allStatus: "All Status",
    newestFirst: "Newest First",
    oldestFirst: "Oldest First",
    mostTasks: "Most Tasks",
    fewestTasks: "Fewest Tasks",
    createProject: "Create Project",
    tasks: "tasks",
    viewDetails: "View Details",
    createNewProject: "Create New Project",
    projectCreatedSuccess: "Project created successfully!",
    invalidRoute: "invalid-route",

    // Project Specific Page
    projectNotFound: "Project not found or does not exist.",
    backToList: "Back to list",
    editProject: "Edit Project",
    projectDetails: "Project Details",
    noDescription: "No description available.",
    projectDescriptionPlaceholder: "Enter project description",
    projectManager: "Project Manager",
    selectManagers: "Select managers",
    notSpecified: "Not specified",
    expectedEndDate: "Expected End Date",
    projectUpdatedSuccess: "Project updated successfully",

    // Task Overview Page
    todo: "To Do",
    blocked: "Blocked",
    searchTasks: "Search tasks...",
    all: "All",
    createTask: "Create Task",
    createNewTask: "Create New Task",
    taskCreatedSuccess: "Task created successfully!",
    taskUpdatedSuccess: "Task updated successfully",
    you: "You",
    justNow: "Just now",
    taskNotFound: "Task not found or does not exist",
    backToProject: "Back to project",
    editTask: "Edit Task",
    taskDetails: "Task Details",
    taskName: "Task Name",
    taskDescriptionPlaceholder: "Enter task description",
    attachments: "Attachments",
    noAttachments: "No attachments",
    selectFile: "Select File",
    searchPlaceholder: "Search for anything...",
    like: "Like",
    featureInDevelopment: "Feature is under development",
    reply: "Reply",
    noComments: "No comments yet",
    writeComment: "Write a comment...",
    review: "Review",
    taskPriorityHigh: "High",
    taskPriorityMedium: "Medium",
    taskPriorityLow: "Low",
    unknownUser: "Unknown User",

    // Modal translations
    modalProjectTitle: "Project Title",
    modalInputProjectTitle: "Please input project title",
    modalEnterProjectTitle: "Enter project title",
    modalProjectType: "Project Type",
    modalSelectProjectType: "Select project type",
    modalWeb: "Web",
    modalApp: "App",
    modalStartDate: "Start Date",
    modalSelectStartDate: "Please select start date",
    modalEndDate: "End Date",
    modalSelectEndDate: "Please select end date",
    modalProjectDescription: "Project Description",
    modalEnterProjectDescription: "Enter project description...",
    modalAddProjectMember: "Add Project Member",
    modalMemberName: "Member Name",
    modalEnterMemberName: "Enter member name",
    modalSelectRole: "Select role",
    modalMemberRole: "Member Role",
    modalInputMemberName: "Please input member name",
    modalSelectMemberRole: "Please select member role",
    modalMemberEmail: "Member Email",
    modalInputMemberEmail: "Please input member email",
    modalEnterMemberEmail: "Enter member email",
    modalInvalidEmail: "Please enter a valid email",
    modalEnterNameAndRole: "Please enter both name and role",
    modalAdd: "Add",
    modalClear: "Clear",
    modalCreate: "Create",

    // Task modal translations
    modalTaskTitle: "Task Title",
    modalInputTaskTitle: "Please input task title",
    modalEnterTaskTitle: "Enter task title",
    modalTaskPriority: "Task Priority",
    modalSelectTaskPriority: "Please select task priority",
    modalSelectPriority: "Select priority",
    modalTaskStatus: "Task Status",
    modalSelectTaskStatus: "Please select task status",
    modalSelectStatus: "Select status",
    modalTaskAssignee: "Task Assignee",
    modalSelectTaskAssignee: "Please select task assignee",
    modalSelectAssignee: "Select assignee",
    modalTaskDescription: "Task Description",
    modalEnterTaskDescription: "Enter task description...",
    modalDateDescription: "Select date",

    // Success messages
    memberAddedSuccess: "Member added successfully!",
  },
  vi: {
    // Navigation & Paths
    navProjects: "Dự án",
    navTasks: "Công việc",
    navPerformance: "Hiệu suất",
    navWorklogs: "Nhật ký công việc",
    navSettings: "Cài đặt",
    navProfile: "Hồ sơ",
    navNotifications: "Thông báo",
    navAppearance: "Giao diện",
    navPrivacy: "Riêng tư",
    navTimezone: "Múi giờ",
    navSecurity: "Bảo mật",

    // Common
    commonSettings: "Cài đặt",
    commonSave: "Lưu",
    commonCancel: "Hủy",
    commonEdit: "Sửa",
    commonDelete: "Xóa",
    commonSearch: "Tìm kiếm",
    commonFilter: "Lọc",
    commonReset: "Đặt lại",
    commonLoading: "Đang tải...",
    commonError: "Lỗi",
    commonSuccess: "Thành công",

    // Settings Menu
    settingsMyProfile: "Hồ sơ của tôi",
    settingsNotifications: "Thông báo",
    settingsAppearance: "Giao diện",
    settingsPrivacy: "Riêng tư",
    settingsTimeZone: "Múi giờ",
    settingsSecurity: "Bảo mật",

    // Profile
    profileFullName: "Họ và tên",
    profileEmail: "Địa chỉ email",
    profilePhone: "Số điện thoại",
    profileLocation: "Vị trí",
    profileRole: "Vai trò",
    profileEdit: "Chỉnh sửa hồ sơ",
    profileUpdate: "Cập nhật hồ sơ",
    profileUpdateSuccess: "Cập nhật hồ sơ thành công",
    profileUpdateFailed: "Cập nhật hồ sơ thất bại",
    profileAbout: "Thông tin thêm",

    // Notifications
    notifEmail: "Thông báo qua email",
    notifPush: "Thông báo đẩy",
    notifDesktop: "Thông báo trên máy tính",
    notifDailyDigest: "Tóm tắt hàng ngày",
    notifTaskUpdates: "Cập nhật công việc",
    notifProjectUpdates: "Cập nhật dự án",
    notifMentions: "Đề cập",
    notifComments: "Bình luận",
    notifMarkAllRead: "Đánh dấu tất cả đã đọc",
    notifNoNotifications: "Không có thông báo",
    notifViewAll: "Xem Nhật ký công việc",
    notifSettings: "Cài đặt thông báo",
    notifEnableAll: "Bật tất cả",
    notifDisableAll: "Tắt tất cả",
    notifTaskAssigned: "Được giao công việc",
    notifTaskCompleted: "Công việc hoàn thành",
    notifTaskUpdated: "Công việc được cập nhật",
    notifTaskComment: "Bình luận mới",
    notifProjectCreated: "Dự án được tạo",
    notifProjectUpdated: "Dự án được cập nhật",
    notifProjectDeleted: "Dự án bị xóa",
    notifMemberAdded: "Thêm thành viên mới",
    notifMemberRemoved: "Xóa thành viên",
    notifRoleChanged: "Thay đổi vai trò",
    notifDeadlineApproaching: "Sắp đến hạn",
    notifOverdue: "Công việc quá hạn",
    notifNewMessage: "Tin nhắn mới",
    notifNewReply: "Phản hồi mới",
    notifNewMention: "Đề cập mới",
    notifNewAttachment: "Tệp đính kèm mới",
    notifNewInvitation: "Lời mời mới",
    notifInvitationAccepted: "Chấp nhận lời mời",
    notifInvitationRejected: "Từ chối lời mời",

    // Appearance
    theme: "Giao diện",
    light: "Sáng",
    dark: "Tối",
    system: "Hệ thống",
    language: "Ngôn ngữ",
    fontSize: "Cỡ chữ",
    small: "Nhỏ",
    fontSizeMedium: "Vừa",
    large: "Lớn",
    density: "Mật độ",
    comfortable: "Thoải mái",
    compact: "Gọn",
    colorScheme: "Bảng màu",

    // Privacy
    profileVisibility: "Hiển thị hồ sơ",
    public: "Công khai",
    teamOnly: "Chỉ nhóm",
    private: "Riêng tư",
    contactInformation: "Thông tin liên hệ",
    showEmail: "Hiển thị email",
    showPhone: "Hiển thị số điện thoại",
    activity: "Hoạt động",
    showActivity: "Hiển thị trạng thái hoạt động",
    showLocation: "Hiển thị vị trí",

    // Security
    twoFactorAuth: "Xác thực hai yếu tố",
    enable2FA: "Bật xác thực hai yếu tố",
    authMethod: "Phương thức xác thực",
    authenticator: "Ứng dụng xác thực",
    sms: "SMS",
    email: "Email",
    sessionSettings: "Cài đặt phiên",
    sessionTimeout: "Thời gian chờ phiên",
    minutes: "phút",
    loginNotifications: "Thông báo đăng nhập",
    password: "Mật khẩu",
    changePassword: "Đổi mật khẩu",
    lastChanged: "Lần thay đổi cuối",

    // Time Zone
    timezone: "Múi giờ",
    dateFormat: "Định dạng ngày",
    timeFormat: "Định dạng giờ",
    hour12: "12 giờ (AM/PM)",
    hour24: "24 giờ",
    weekStartsOn: "Tuần bắt đầu vào",
    monday: "Thứ Hai",
    sunday: "Chủ Nhật",

    // Home Page
    welcomeBack: "Chào mừng trở lại",
    quickOverview: "Đây là tổng quan nhanh về ngày của bạn",
    projects: "Dự án",
    ongoing: "đang thực hiện",
    completedTasks: "Công việc đã hoàn thành",
    today: "hôm nay",
    activeMembers: "Thành viên đang hoạt động",
    members: "thành viên",
    reports: "Báo cáo",
    generated: "đã tạo",
    todaySchedule: "Lịch trình hôm nay",
    recentActivity: "Hoạt động gần đây",
    dueToday: "Hết hạn hôm nay",
    quote:
      '"Cách tốt nhất để bắt đầu là ngừng nói và bắt đầu làm." – Walt Disney',

    // Performance Page
    projectName: "Tên dự án",
    status: "Trạng thái",
    progress: "Tiến độ",
    startDate: "Ngày bắt đầu",
    endDate: "Ngày kết thúc",
    manager: "Quản lý",
    overdueTasks: "Công việc quá hạn",
    unknown: "Không xác định",
    completed: "Đã hoàn thành",
    inProgress: "Đang thực hiện",
    overdue: "Quá hạn",
    open: "Mở",
    totalProjects: "Tổng số dự án",
    averageProgress: "Tiến độ trung bình",
    projectPerformanceOverview: "Tổng quan hiệu suất dự án",
    taskStatusDistribution: "Phân bố trạng thái công việc",
    monthlyProgress: "Tiến độ theo tháng",

    // WorkLogs Page
    project: "Dự án",
    task: "Công việc",
    user: "Người dùng",
    description: "Mô tả",
    createdAt: "Ngày tạo",
    export: "Xuất",
    exportComingSoon: "Tính năng xuất sẽ sớm có mặt",
    totalHours: "Tổng số giờ",
    activeUsers: "Người dùng đang hoạt động",
    searchWorkLogs: "Tìm kiếm nhật ký công việc...",
    filters: "Bộ lọc",
    active: "Đang hoạt động",
    inactive: "Không hoạt động",

    // Login Page
    projectManagement: "Quản lý dự án",
    signInToAccount: "Đăng nhập vào tài khoản của bạn",
    pleaseInputEmail: "Vui lòng nhập email của bạn!",
    pleaseEnterValidEmail: "Vui lòng nhập email hợp lệ!",
    pleaseInputPassword: "Vui lòng nhập mật khẩu của bạn!",
    signIn: "Đăng nhập",
    login: "Đăng nhập",
    signUp: "Đăng ký",
    loginSubtitle: "Chào mừng trở lại! Vui lòng nhập thông tin của bạn.",
    name: "Tên",
    namePlaceholder: "Nhập tên của bạn",
    email: "Email",
    emailPlaceholder: "Nhập email của bạn",
    password: "Mật khẩu",
    passwordPlaceholder: "Nhập mật khẩu của bạn",
    confirmPassword: "Xác nhận mật khẩu",
    confirmPasswordPlaceholder: "Xác nhận mật khẩu của bạn",
    noAccount: "Chưa có tài khoản?",
    haveAccount: "Đã có tài khoản?",
    pleaseInputName: "Vui lòng nhập tên của bạn!",
    pleaseConfirmPassword: "Vui lòng xác nhận mật khẩu của bạn!",
    passwordMinLength: "Mật khẩu phải có ít nhất 6 ký tự!",
    passwordsDoNotMatch: "Hai mật khẩu không khớp!",
    loginSuccess: "Đăng nhập thành công!",
    signupSuccess: "Đăng ký thành công!",
    loginFailed: "Đăng nhập thất bại",
    signupFailed: "Đăng ký thất bại",
    unknownError: "Đã xảy ra lỗi không xác định",

    // NotFound Page
    pageNotFound: "Xin lỗi, trang bạn truy cập không tồn tại.",
    backToHome: "Về trang chủ",
    goBack: "Quay lại",

    // Project Management Page
    onHold: "Tạm dừng",
    cancelled: "Đã hủy",
    development: "Phát triển",
    design: "Thiết kế",
    marketing: "Marketing",
    research: "Nghiên cứu",
    allStatus: "Tất cả trạng thái",
    newestFirst: "Mới nhất trước",
    oldestFirst: "Cũ nhất trước",
    mostTasks: "Nhiều công việc nhất",
    fewestTasks: "Ít công việc nhất",
    createProject: "Tạo dự án",
    tasks: "công việc",
    viewDetails: "Xem chi tiết",
    createNewProject: "Tạo dự án mới",
    projectCreatedSuccess: "Tạo dự án thành công!",
    invalidRoute: "đường-dẫn-không-hợp-lệ",

    // Project Specific Page
    projectNotFound: "Dự án không tồn tại hoặc không tìm thấy.",
    backToList: "Quay lại danh sách",
    editProject: "Chỉnh sửa dự án",
    projectDetails: "Chi tiết dự án",
    noDescription: "Chưa có mô tả.",
    projectDescriptionPlaceholder: "Nhập mô tả dự án",
    projectManager: "Người quản lý",
    selectManagers: "Chọn người quản lý",
    notSpecified: "Chưa xác định",
    expectedEndDate: "Ngày kết thúc dự kiến",
    projectUpdatedSuccess: "Cập nhật dự án thành công",

    // Task Overview Page
    todo: "Cần làm",
    blocked: "Bị chặn",
    searchTasks: "Tìm kiếm công việc...",
    all: "Tất cả",
    createTask: "Tạo công việc",
    createNewTask: "Tạo công việc mới",
    taskCreatedSuccess: "Tạo công việc thành công!",
    taskUpdatedSuccess: "Cập nhật task thành công",
    you: "Bạn",
    justNow: "Vừa xong",
    taskNotFound: "Task không tồn tại hoặc không tìm thấy",
    backToProject: "Quay lại dự án",
    editTask: "Chỉnh sửa task",
    taskDetails: "Chi tiết task",
    taskName: "Tên task",
    taskDescriptionPlaceholder: "Nhập mô tả chi tiết task",
    attachments: "File đính kèm",
    noAttachments: "Chưa có file đính kèm",
    selectFile: "Chọn file",
    searchPlaceholder: "Tìm kiếm...",
    like: "Thích",
    featureInDevelopment: "Tính năng đang phát triển",
    reply: "Trả lời",
    noComments: "Chưa có bình luận nào",
    writeComment: "Viết bình luận...",
    review: "Đang xem xét",
    taskPriorityHigh: "Cao",
    taskPriorityMedium: "Trung bình",
    taskPriorityLow: "Thấp",
    unknownUser: "Người dùng không xác định",

    // Modal translations
    modalProjectTitle: "Tiêu đề dự án",
    modalInputProjectTitle: "Vui lòng nhập tiêu đề dự án",
    modalEnterProjectTitle: "Nhập tiêu đề dự án",
    modalProjectType: "Loại dự án",
    modalSelectProjectType: "Chọn loại dự án",
    modalWeb: "Web",
    modalApp: "Ứng dụng",
    modalStartDate: "Ngày bắt đầu",
    modalSelectStartDate: "Vui lòng chọn ngày bắt đầu",
    modalEndDate: "Ngày kết thúc",
    modalSelectEndDate: "Vui lòng chọn ngày kết thúc",
    modalProjectDescription: "Mô tả dự án",
    modalEnterProjectDescription: "Nhập mô tả dự án...",
    modalAddProjectMember: "Thêm thành viên dự án",
    modalMemberName: "Tên thành viên",
    modalEnterMemberName: "Nhập tên thành viên",
    modalSelectRole: "Chọn vai trò",
    modalMemberRole: "Vai trò thành viên",
    modalInputMemberName: "Vui lòng nhập tên thành viên",
    modalSelectMemberRole: "Vui lòng chọn vai trò thành viên",
    modalMemberEmail: "Email thành viên",
    modalInputMemberEmail: "Vui lòng nhập email thành viên",
    modalEnterMemberEmail: "Nhập email thành viên",
    modalInvalidEmail: "Vui lòng nhập email hợp lệ",
    modalEnterNameAndRole: "Vui lòng nhập cả tên và vai trò",
    modalAdd: "Thêm",
    modalClear: "Xóa",
    modalCreate: "Tạo",

    // Task modal translations
    modalTaskTitle: "Tiêu đề công việc",
    modalInputTaskTitle: "Vui lòng nhập tiêu đề công việc",
    modalEnterTaskTitle: "Nhập tiêu đề công việc",
    modalTaskPriority: "Độ ưu tiên",
    modalSelectTaskPriority: "Vui lòng chọn độ ưu tiên",
    modalSelectPriority: "Chọn độ ưu tiên",
    modalTaskStatus: "Trạng thái",
    modalSelectTaskStatus: "Vui lòng chọn trạng thái",
    modalSelectStatus: "Chọn trạng thái",
    modalTaskAssignee: "Người thực hiện",
    modalSelectTaskAssignee: "Vui lòng chọn người thực hiện",
    modalSelectAssignee: "Chọn người thực hiện",
    modalTaskDescription: "Mô tả công việc",
    modalEnterTaskDescription: "Nhập mô tả công việc...",
    modalDateDescription: "Chọn ngày",

    // Success messages
    memberAddedSuccess: "Thêm thành viên thành công!",
  },
};

export const LanguageProvider = ({ children }) => {
  // Get initial language from localStorage or default to 'en'
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem("language");
    return savedLanguage || "en";
  });

  // Save language to localStorage whenever it changes
  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || key;
  };

  const changeLanguage = (lang) => {
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, t, changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
